import { AgentDefinition, SkillDefinition } from '../types.js';

export class ContextGenerator {
    static generateClaudeMd(agents: AgentDefinition[], skills: SkillDefinition[]): string {
        let content = "# Project Context\n\n";
        content += "This file is auto-generated by the aios. Do not edit manually.\n\n";
        
        content += "## Available Agents\n";
        agents.forEach(agent => {
            content += `### ${agent.name}\n`;
            content += `${agent.description}\n\n`;
            content += `**Instructions:**\n${agent.instructions}\n\n`;
        });

        content += "## Available Skills\n";
        skills.forEach(skill => {
            content += `### ${skill.name}\n`;
            // Assuming skill content is markdown or code
            content += `${skill.content}\n\n`;
        });

        return content;
    }

    static generateCursorRules(agents: AgentDefinition[], skills: SkillDefinition[]): string {
        let content = "# .cursorrules\n\n";
        content += "This file is auto-generated by the aios.\n\n";

        content += "## Project Standards\n";
        content += "- Use TypeScript for all new code.\n";
        content += "- Follow the Manager pattern in `packages/core`.\n\n";

        content += "## Agent Capabilities\n";
        agents.forEach(agent => {
            content += `- ${agent.name}: ${agent.description}\n`;
        });

        return content;
    }
}
