name: PR Build and Test

on:
  pull_request:
    branches: [master, 'release-*']

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.15.1'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Type check
        run: pnpm type-check

  build-and-test-go:
    name: Build and Test Go MCP Host
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('mcp-host-go/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        working-directory: mcp-host-go
        run: make deps

      - name: Build Go MCP Host
        working-directory: mcp-host-go
        run: make build

      - name: Run Go tests
        working-directory: mcp-host-go
        run: make test
